sudo: true
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest requests decorator -y
  - source activate test
  - conda install -c conda-forge google-auth google-auth-oauthlib=0.4.0 google-cloud-core
    google-api-core google-api-python-client -y
  - pip install git+https://github.com/intake/filesystem_spec --no-deps
script:
  - py.test -vv gdrivefs
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_5ddb9a250ae2_key -iv $encrypted_5ddb9a250ae2_iv
  -in .google_drive_tokens.enc -out tfile.pickle -d
